### PR TITLE
Update demo docs w/ teleop usage info

### PR DESCRIPTION
**Pull request by kevin-thankyou-lin**
Update demo docs w/ teleop usage info

### CODE REVIEW

**Review by snasiriany — CHANGES_REQUESTED** [review]
The rest of the docs pertaining to this demo_device_control.py need to be updated:
* example commands have `--controller osc` which is incorrect
* it talks about ik vs osc ("user inputs with ik’s rotations are always taken relative to eef coordinate frame, whereas user inputs with osc’s rotations are taken relative to global frame (i.e., static / camera frame of reference).") which at this point is out of date info and needs to be removed I think.

these are at least the parts I found. Can you please update the PR with all of the changes needed for this section?

**Comment by kevin-thankyou-lin** [comment]
@snasiriany updated

**Review by snasiriany — CHANGES_REQUESTED** [review]
@kevin-thankyou-lin there's a section slightly above that needs to be updated: "The commands are mapped to joint velocities through an inverse kinematics solver from Bullet physics."

**Comment by kevin-thankyou-lin** [comment]
@snasiriany can you merge this?

**Review by snasiriany — APPROVED** [review]

**Comment by snasiriany** [comment]
@kevin-thankyou-lin done!

**Pull request merged**
