### PR TITLE
repair deterministic playback

### PR DESCRIPTION
**Pull request by amandlek**
- fix some errors that we had in our scripts and data collection from the v1.0 refactor to enable deterministic action playback
- address #173 and #162

### CODE REVIEW

**Comment by yukezhu** [comment]
Thanks for the quick repair. @zhuyifengzju should test this PR as well.

**Comment by yukezhu** [comment]
Shall we close PR #167 given this one?

**Review by zhuyifengzju — APPROVED** [review]
I tested localy, and this PR fixed the issue. And I think the #167 is also resolved in this PR.

**Review by yukezhu — CHANGES_REQUESTED** [review]
Is this assertion too harsh? Maybe we should allow for some tolerance for small numerical errors in checking the state matching.

https://github.com/ARISE-Initiative/robosuite/blob/e8bf463ab55b5b35090e9686a5ed70b67220f527/robosuite/scripts/playback_demonstrations_from_hdf5.py#L94

Also, tried the replay function with one demonstration collected with the keyboard (download this [demonstration](https://utexas.box.com/s/qjppgbae1zh65k1brzgvnvinnvtwuuzw) file) and this assertion throws exception.

**Review by yukezhu — APPROVED** [review]

**Pull request merged**
