### PR TITLE
Remove unneeded print

### PR DESCRIPTION
**Pull request by kevin-thankyou-lin**
## What this does
Removes unneeded print

### CODE REVIEW

**Comment by kevin-thankyou-lin** [comment]
@youliangtan I removed one print statement to avoid clogging the terminal - could you take a look?

**Review by youliangtan — APPROVED** [review]

**Comment by kevin-thankyou-lin** [comment]
Oops @youliangtan looks like you don't have write access --- asking @zhuyifengzju to take a look

**Comment by zhuyifengzju** [comment]
Shall we change it to debug logging messages?

**Comment by kevin-thankyou-lin** [comment]
Looking at the other `.debug()`, these are only used when there's something unexpected e.g.

```
                if part_name not in self._action_split_indexes:
                    ROBOSUITE_DEFAULT_LOGGER.debug(f"{part_name} is not specified in the action space")
                    continue
```

so I think using `.debug()` mightn't fit? Also, not sure how useful logging this is anyways - we only have this print statement for one file

**Review by zhuyifengzju — APPROVED** [review]

**Pull request merged**
