### PR TITLE
replaced mujoco-py with free-mujoco-py version 2.1.0 from DM

### LINKED ISSUE #262: Fixing robosuite dependencies with mujoco210.
Since DeepMind has acquired MuJoCo, they have a new release version, a.k.a mujoco210.  When installing robosuite, it is looking for mujoco200.  Would you be able to fix the dependencies?

### PR DESCRIPTION
**Pull request by raghavauppuluri13**
Updates dependencies for compatibility with new free version of Mujoco. more info: https://github.com/openai/mujoco-py/pull/640. Resolves #262

### CODE REVIEW

**Comment by yukezhu** [comment]
Hi @raghavauppuluri13 thank you for submitting this PR! Can you also update the [installation guide](https://github.com/ARISE-Initiative/robosuite/blob/master/docs/installation.md) with this PR? The free-mujoco-py library does not require manual downloading of mujoco anymore.

**Comment by raghavauppuluri13** [comment]
@yukezhu Let me know if that looks good.

**Review by yukezhu — APPROVED** [review]
LGTM

**Comment by yukezhu** [comment]
Merged. Thanks for your contribution!

**Comment by raghavauppuluri13** [comment]
My pleasure! Also, I was wondering if your group had performance concerns with using mujoco-py given that it is unstable. One issue that stood out was differences in performance on baselines if you render it or not, plus a multitude of performance and installation issues. OpenAI doesn't plan to put more effort into it according to the group at openai gym. The https://github.com/deepmind/dm_control API was a breeze for myself to setup and work with. I can also make this a separate issue if it's something of further interest.

**Pull request merged**
